<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Pos.Core.Analytics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pos.Core.Data\Pos.Core.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pos.Core.Tests" />
  </ItemGroup>

</Project>
